### ISSUE TITLE
healpy section - change name

### ISSUE THREAD

**Issue by damonge** [xC-ell/xCell#109]
The name of the `healpy` section doesn't make much sense to me, since we don't really use healpy for SHTs. I'd call it `sht` or something like that.

**Comment by carlosggarcia** [comment]
Not sure what `healpy` section you're talking about

**Comment by damonge** [comment]
the one in the yaml file that contains the `niter` options

**Comment by damonge** [comment]
This one: https://github.com/xC-ell/xCell/blob/61b6e566f50f6f11276e98e62425b8bc7a70b882/input/desy1_ebossqso_p18cmbk.yml#L207
