### ISSUE TITLE
persistent yml files

### ISSUE THREAD

**Issue by damonge** [xC-ell/xCell#112]
Some of the consequences of reading parameters from a yaml file if it exists (rather than taking them from the input dictionary) can be a bit confusing. For instance, if you create a `Covariance` object, while it is initialized, it will create `Cl` objects, which will then throw a warning, because they will read parameters from the yaml file created by the `Covariance` objects rather than the dictionary. Is this intended? Do we want to add a flag that says `ignore_existing_yaml` or something like that for these cases?

**Comment by carlosggarcia** [comment]
I think we can just input a dictionary and let the user/script to read the YAML file.

**Comment by damonge** [comment]
but the point is that, you create `Covariance` with a dictionary, then covariance writes a yaml file, then it creates a `Cl` with the same dictionary, but instead the `Cl` will read the yaml file (because it exists). It's not a huge deal, but it does mean that we throw that warning very often.
