### ISSUE TITLE
mapper: allow auto- and cross-correlation to use different maps

### ISSUE THREAD

**Issue by carlosggarcia** [xC-ell/xCell#121]
There are mappers, as CMB tSZ, where you will want to use different maps for auto and cross correlations to estimate the noise signal.

**Comment by carlosggarcia** [comment]
this is already implemented in https://github.com/xC-ell/xCell/blob/4030baf4ad9d1459b0093dec16b22415162b31ec/xcell/cls/cl.py#L187, right, @damonge?

**Comment by damonge** [comment]
Yep
