### ISSUE TITLE
SDSS Autocorrelation 

### ISSUE THREAD

**Issue by JaimeRZP** [xC-ell/xCell#149]
Look if we still see problematic behaviour.

**Comment by damonge** [comment]
BOSS and eBOSS auto-correlations seem OK. The main problem probably has to do with the shot noise subtraction, which we know we just need to marginalize over anyway.

![boss_autos](https://user-images.githubusercontent.com/8809493/133626542-33ea17ad-6bad-41ff-a338-0bcc496588de.png)
![auto_eboss](https://user-images.githubusercontent.com/8809493/133626540-7902cc5b-099a-49e2-9084-b3ecf25e795e.png)

Nevertheless the error bars for the auto-correlation seem too small here, so I'll investigate why

**Comment by damonge** [comment]
OK, this looks better.
![eboss_auto](https://user-images.githubusercontent.com/8809493/133634775-fe99c77d-33ad-4627-b1ea-01255a27cd84.png)
I think we can close this issue
