### ISSUE TITLE
Implemented but not validated mappers

### ISSUE THREAD

**Issue by damonge** [xC-ell/xCell#153]
We have not really validated the following:
- Planck SMICA map. We could do this by trying to reproduce one of the existing ISW papers.
- Planck CIB map. We should check the Planck papers or any others where this map has been used.
- Planck tSZ map. This is mostly validated, but it would be nice to check that we can get the auto-correlation right too.

**Comment by JaimeRZP** [comment]
Regarding the CIB
https://arxiv.org/pdf/1609.08942.pdf

**Comment by damonge** [comment]
I think we can close this, right @JaimeRZP ?
