### ISSUE TITLE
Parallel run: check if other process has started writing one of the output files

### ISSUE THREAD

**Issue by carlosggarcia** [xC-ell/xCell#185]
When launching all runs in parallel, sometimes two processes try to write the workspace at the same time. That makes them fail. We should recheck if the file exists before trying to write. Ideally, we would want just one of the processes do the work and the other wait to read the file, but that's much more effort.

**Comment by carlosggarcia** [comment]
@damonge are you happy to close this issue?

**Comment by damonge** [comment]
yep
