### ISSUE TITLE
CIB_Lenz: Double masking

### ISSUE THREAD

**Issue by JaimeRZP** [xC-ell/xCell#186]
We are premasking CIB_lenz maps in their native nside. 
However, CIB_lenz doesn't have a seperate point_source mask.
Thus we are applying the whole mask before hand. 
Then we are applying the mask again in our cl pipeline.
This is applies the mask twice.

**Comment by damonge** [comment]
@JaimeRZP is this solved?

**Comment by JaimeRZP** [comment]
Not yet I am afraid

**Comment by JaimeRZP** [comment]
We need SPT and CIB_Lenz to apply the ps_mask to the maps before up/down-grading the resolution. 
The way to tackle it is to:
- Remove the `get_signal_map()` from `Planck_base` --> Make it particular to:
- P15tSZ --> Just copy what currently is base
- P18CMBk --> Just copy what currently is base
- P18SMICA --> Just copy what currently is base
- SPT --> Create a method for `get_signal_map` that seeks for a file. if not run a private method that masks it. Do not apply the ps_mask later on.
- CIB_Lenz --> Same as above but we don't have a separate ps_mask. **Question:** what do we do here?

**Comment by damonge** [comment]
OK, I think the strategy then is to leave `get_signal_map` there, and just overload that function for `SPT` and `CIB_Lenz`

**Comment by damonge** [comment]
For CIBLenz, I think I'd just not worry about masking the PSs at all and live with it. We've only seen this to be a problem for SPT. Unlike in the case of SPT, in CIBLenz will be either upgrading or leaving the resolution as it is for most of our runs, so it's less of a problem.
