### ISSUE TITLE
Insufficient shared sources shot noise Nl (?)

### ISSUE THREAD

**Issue by JaimeRZP** [xC-ell/xCell#204]
![image](https://user-images.githubusercontent.com/39957598/158856383-11e184bd-1dc1-4b2d-bd8e-172aed17c62b.png)
![image](https://user-images.githubusercontent.com/39957598/158856423-36fcc176-1de1-456e-98cd-9e2d9e4d671e.png)
![image](https://user-images.githubusercontent.com/39957598/158856436-def507a2-a259-497a-b84b-3265d7c37d6d.png)
![image](https://user-images.githubusercontent.com/39957598/158856451-5a8ae64e-5852-4b0e-8d38-38ce65f5b7f1.png)

Hypothesis: we expect that at high l's the cross-correlation Cl of mappers sharing sources should match noise power spectrum due to the shot noise of said shared sources. 
Problem: The two don't seem to match.

**Comment by damonge** [comment]
We decided to drop this
