### ISSUE TITLE
Should all mappers have rerun options for masks?

### ISSUE THREAD

**Issue by damonge** [xC-ell/xCell#214]
Fact 1: a majority of our catalog-based mappers use equatorial coordinates. Most map-based mappers use galactic coordinates.
Fact 2: it is more precise to rotate the coordinates and ellipticities of a catalog than to rotate a map (the latter involves interpolation or lossy spherical harmonic transforms).
Fact 3: map rotations are kind of slow.
Conclusion: it will be best to use galactic coordinates as a basis for our power spectra. However, this means that we will have to rotate the masks of all mappers using equatorial coordinates. Since this is a bit slow, we could save those masks. Since many of these masks are binary, saving them in `fits.gz` format will probably be quite efficient.

Question 1: should all mappers have the possibility of saving rerun versions of their masks?
Question 2: should we make the rerun path a global parameter, so all rerun files are dumped in the same place?

This would have the added advantages of:
a) Faster C_ells and covariances (since masks are computed every time)
b) Homogeneous naming scheme for rerun files.

**Comment by carlosggarcia** [comment]
Not sure I understand what you mean.

**Comment by damonge** [comment]
oh, I misunderstood you. You mean that you'd prefer each mapper to have its own potentially different rerun directory, right?

**Comment by carlosggarcia** [comment]
Yes. Something as you have now with `Datasets/DES_Y1/xcell_reruns`
