### ISSUE TITLE
Create all mapper yaml files

### ISSUE THREAD

**Issue by damonge** [xC-ell/xCell#216]
We should create default yaml files for all mappers that can then be imported into the global yaml file.

**Comment by carlosggarcia** [comment]
List of mappers we have to do:

- [ ] mapper_2MPZ.py
- [ ] mapper_ACTCMB.py
- [ ] mapper_ACT_compsept.py
- [ ] mapper_ACTk.py
- [ ] mapper_ACTtSZ.py
- [ ] mapper_BOSS.py
- [ ] mapper_CatWISE.py
- [ ] mapper_CIBLenz.py
- [ ] mapper_DELS.py
- [ ] mapper_DESY1gc.py
- [ ] mapper_DESY1wl.py
- [ ] mapper_eBOSS.py
- [ ] mapper_HSC_DR1wl.py
- [ ] mapper_KiDS1000.py
- [ ] mapper_KV450.py
- [ ] mapper_NVSS.py
- [ ] mapper_P15CIB.py
- [ ] mapper_P15tSZ.py
- [ ] mapper_P18CMBK.py
- [ ] mapper_P18SMICA.py
- [ ] mapper_ROSAT.py
- [ ] mapper_SDSS.py
- [ ] mapper_SPT.py
- [ ] mapper_WIxSC.py

I'll be doing those in the S8z paper:
- [ ] mapper_P18CMBK.py
- [ ] mapper_DELS.py
- [ ] mapper_DESY1gc.py
- [ ] mapper_DESY1wl.py
- [ ] mapper_KiDS1000.py
- [ ] mapper_KV450.py
- [ ] mapper_eBOSS.py

**Comment by damonge** [comment]
Note that we won't do KV450 (we have KiDS1000)
