### ISSUE TITLE
P15CIB inconsistencies

### ISSUE THREAD

**Issue by JaimeRZP** [xC-ell/xCell#223]
At the moment our mapper is desinged to take in the gp and ps masks from the  [frequency maps](https://wiki.cosmos.esa.int/planck-legacy-archive/index.php/Frequency_maps#Masks). 

```           
self.gp_mask_mode = config.get('gp_mask_mode', '0.6')
self.gp_mask_modes = {'0.2': 0,
                      '0.4': 1,
                      '0.6': 2,
                      '0.7': 3,
                      '0.8': 4,
                      '0.9': 5,
                      '0.97': 6,
                      '0.99': 7}
self.ps_mask_mode = config.get('ps_mask_mode', ['545'])
self.ps_mask_modes = {'100': 0,
                      '143': 1,
                      '217': 2,
                      '353': 3,
                      '545': 4,
                      '857': 5}
```    
However, the maps are component separated maps, not frequency ones, and can be found [here](https://irsa.ipac.caltech.edu/data/Planck/release_2/all-sky-maps/ysz_previews/). They have the following particularities:

- The full and half missions are different fields of the same file
- NILC maps have their own mask as an extra field
- MILCA maps just use the the masks in the masks folder.
- The mask in the masks folder contains both the gp and ps mask in different fields.

At the moment our mapper is essentially broken becuause it wouldn't work with either MILCA or NILC maps. 
Since we have CIB Lenz which is better, I suggest we just get rid of this mapper until we decide to properly implement it.

**Comment by damonge** [comment]
OK, sounds good. Get rid of it (but you need to ditch the associated tests)
