### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by JaimeRZP** [xC-ell/xCell#234]
We need to write the documentation for this code. 
Modules for which there's at least some documentation:

**xcell/mappers**
- [x] mapper_2MPZ.py
- [x] mapper_ACTCMB.py
- [x] mapper_ACT_base.py
- [x] mapper_ACT_compsept.py
- [x] mapper_ATCk.py
- [x] mapper_ACTtSZ.py
- [x] mapper_BOSS.py
- [x] mapper_CIBLenz.py
- [x] mapper_CATWISE.py
- [x] mapper_DELS.py
- [x] mapper_DESY1gc.py
- [x] mapper_DESY1wl.py
- [x] mapper_HSC_DR1wl.py
- [x] mapper_KV450.py
- [x] mapper_KIDS1000.py
- [x] mapper_NVSS.py
- [x] mapper_P15CIB.py
- [x] mapper_P15tSZ.py
- [x] mapper_P18CMBk.py
- [x] mapper_P18SMICA.py
- [x] mapper_Planck_base.py
- [x] mapper_ROSAT.py
- [x] mapper_SDSS.py
- [x] mapper_SPT.py
- [x] mapper_WIxSC
- [x] mapper_base.py
- [x] mapper_eBOSS.py
- [x] utils.py

**xcell/cls**
- [x] cl.py
- [x] cov.py
- [x] data.py
- [x] theory.py
- [x] to_sacc.py

**Comment by JaimeRZP** [comment]
Shoul we make `_get_hm_maps` a public method and make a dummy documented version in Planck_base?

**Comment by carlosggarcia** [comment]
Writing the documentation for the cls modules on this PR: https://github.com/xC-ell/xCell/pull/238

**Comment by carlosggarcia** [comment]
Done
