### ISSUE TITLE
Planck mapper rotation

### ISSUE THREAD

**Issue by damonge** [xC-ell/xCell#236]
We should save Planck maps after rotating them, since this takes a long time. This only needs to be done when using Galactic coords for the Planck maps, or when using Galactic coords for the SPT map.

**Comment by carlosggarcia** [comment]
Shouldn't this be done for all the mappers when you rotate the mask/map?  (i.e. add a `if coordinates != coordinates_orig: rotate & save`)

**Comment by damonge** [comment]
yes, probably a good idea

**Comment by damonge** [comment]
note that, for the planck maps, we also need to do this for the half-mission maps
