### ISSUE TITLE
DECALS catalogs take forever

### ISSUE THREAD

**Issue by carlosggarcia** [xC-ell/xCell#66]
Reading the catalogs (I think this is the cause although I didn't look into it too much) takes way long. At least much longer than KV.

**Comment by damonge** [comment]
I think #180 will fix this

**Comment by carlosggarcia** [comment]
@damonge shall we close this?

**Comment by damonge** [comment]
Maybe yes. I think the last PR should have solved it, but we can reopen again if we think it's still not sufficiently fast.
