### ISSUE TITLE
More datasets: Planck tSZ

### ISSUE THREAD

**Issue by damonge** [xC-ell/xCell#78]
https://arxiv.org/abs/1502.01596

See implementation in https://arxiv.org/abs/1909.09102

**Comment by damonge** [comment]
Data here: http://pla.esac.esa.int/pla/#maps (check "SZ")

**Comment by JaimeRZP** [comment]
Maybe we are after comptonSZ (http://pla.esac.esa.int/pla/#maps) instead?

**Comment by damonge** [comment]
Ah yes! Start with the MILCA map
