### ISSUE TITLE
More datasets: BOSS CMASS and LOWZ

### ISSUE THREAD

**Issue by damonge** [xC-ell/xCell#80]
Data here: https://data.sdss.org/sas/dr12/boss/lss/

BOSS papers here: http://www.sdss3.org/science/boss_publications.php

**Comment by JaimeRZP** [comment]
Drafted code. Needs testing. 
Found these papers that might be useful:
https://arxiv.org/pdf/1607.03151.pdf
https://arxiv.org/pdf/1509.06529.pdf

**Comment by damonge** [comment]
OK, great! Will you open up a branch?

**Comment by JaimeRZP** [comment]
There's a branch call SDSS_superclass!

**Comment by damonge** [comment]
Let's not close until things are merged
