### ISSUE TITLE
More datasets: CMB lensing from ACT

### ISSUE THREAD

**Issue by damonge** [xC-ell/xCell#83]
Paper: https://arxiv.org/abs/2004.01139

Data: https://lambda.gsfc.nasa.gov/product/act/act_dr4_derived_maps_get.cfm

**Comment by JaimeRZP** [comment]
Found ACT's jupyter notebook tutorials on how to manipulate their data files: https://github.com/ACTCollaboration/DR4_DR5_Notebooks

**Comment by JaimeRZP** [comment]
This has been implemented
