### ISSUE TITLE
Proposal: drop KV450

### ISSUE THREAD

**Issue by damonge** [xC-ell/xCell#90]
Shall we remove KV450, since we already have K1000?

**Comment by JaimeRZP** [comment]
I think it might be interesting as a comparison since K1K covers twice as much sky if I am remembering correctly.  I can imagine people wanting to do consistency tests. I guess that the problem is that we would have to make extra tests for it. Would this be the case or could we reuse K1K ones?

**Comment by damonge** [comment]
We can probably reuse the K1000 ones. OK, let's keep it.
