### ISSUE TITLE
Proposal: modify DECALS

### ISSUE THREAD

**Issue by damonge** [xC-ell/xCell#95]
I'd propose two changes:

1. Rename it to DLS (since DECALS is only part of these data)
2. Remove the possibility of computing N_ell from the data. In practice we never do this, and it'd be dangerous, since these data take a while to become shot-noise dominated.

**Comment by carlosggarcia** [comment]
I'd rename it to DELS instead of DECALS, as in our paper (2103.11195). Recall that there is a different survey called DLS, the Deep Lens Survey (1807.09195)

**Comment by damonge** [comment]
ah, right, yes.
